Fix MySQL setup (#1870)
When installing Trulens over MySQL we get this error:
alembic.util.exc.CommandError: All MySQL CHANGE/MODIFY COLUMN operations require the existing type.

this patch fixes that error.

Co-authored-by: Josh Reini <josh.reini@snowflake.com>