Fix MySQL setup
When installing Trulens over MySQL we get this error:
alembic.util.exc.CommandError: All MySQL CHANGE/MODIFY COLUMN operations require the existing type.

this patch fixes that error.